name: Ejecutar asistencia

on:
  schedule:
    - cron: '0 9 * * 1-5'  # Ejecutar de lunes a viernes a las 9:00 AM (UTC)
    - cron: '0 18 * * 1-5' # Ejecutar de lunes a viernes a las 6:00 PM (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Usar la versión de Node.js que necesitas

      - name: Install dependencies
        run: npm install

      - name: Run attendance script
        env:
          URL: ${{ secrets.URL }}
          RUT: ${{ secrets.RUT }}
        run: node index.js entrada ${{ secrets.RUT }}
